[workspace]
members = [
    "guessing_game",
    "word_counter",
    "calculator_simple",
    "temp_converter",
    "bmi_converter", "palindrome_checker", "fibonacci_generator", "prime_number_checker", "todo_list", "timer_tool", "json_parser", "file_reader", "string_manipulation", "contact_manager",
]
resolver = "2"

[workspace.dependencies]
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.149"
